name: CI/CD Lambda

on:
  push:
    branches:
      - main # Solo despliega cuando haces push a la rama dev

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Cambia según tu región

    - name: Desplegar Lambda
      run: |
        zip function.zip index.js
        aws lambda update-function-code --function-name code-lamda-dev --zip-file fileb://function.zip