name: CI/CD Lambda (dev)

on:
  push:
    branches:
      - main  # Cambia si usas otra rama para desarrollo

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: dev  # 👈 Activa las variables y secretos del entorno "dev"

    env:
      AWS_REGION: ${{ vars.AWS_REGION_DEV }}
      FUNCTION_NAME: ${{ vars.FUNCTION_NAME_DEV }}
      LAMBDA_RUNTIME: ${{ vars.LAMBDA_RUNTIME_DEV }}
      LAMBDA_HANDLER: ${{ vars.LAMBDA_HANDLER_DEV }}
      LAMBDA_ROLE_ARN: ${{ vars.LAMBDA_ROLE_ARN_DEV }}
      LAMBDA_TIMEOUT: ${{ vars.LAMBDA_TIMEOUT_DEV }} 

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Instalar dependencias
      run: npm install

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Empaquetar código
      run: |
        if [ ! -f index.js ]; then
          echo "ERROR: No se encontró index.js"
          exit 1
        fi
        zip -r function.zip index.js

    - name: Crear o actualizar función Lambda
      run: |
        echo "Verificando si existe la función: $FUNCTION_NAME"
        if aws lambda get-function --function-name "$FUNCTION_NAME" --region "$AWS_REGION" > /dev/null 2>&1; then
          echo "✅ La función existe, actualizando código..."
          aws lambda update-function-code \
            --function-name "$FUNCTION_NAME" \
            --zip-file fileb://function.zip \
            --timeout "$LAMBDA_TIMEOUT" \ 
            --region "$AWS_REGION"
        else
          echo "⚠️ La función no existe, creando..."
          aws lambda create-function \
            --function-name "$FUNCTION_NAME" \
            --runtime "$LAMBDA_RUNTIME" \
            --role "$LAMBDA_ROLE_ARN" \
            --handler "$LAMBDA_HANDLER" \
            --zip-file fileb://function.zip \
            --timeout "$LAMBDA_TIMEOUT" \
            --region "$AWS_REGION"
        fi